cmd/pull-macos: delete (#189)
* cmd/pull-macos: delete

- `brew pull` has been deprecated for a while, this fails with:

```
Error: Calling brew pull is disabled! Use gh pr checkout instead.
Please report this issue to the homebrew/linux-dev tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/pull-macos.rb:16

```

* README: Delete mentions of `pull-macos` command