Refactor bits of build-bottle-pr into find-formulae-to-bottle (#112)
* Refactor bits of build-bottle-pr into find-formulae-to-bottle

- In doing Homebrew/linuxbrew-core PR 14838 (a GitHub Action for `brew
  build-bottle-pr`), concerns were raised about a bot with access to our
  repos being able to rewrite formulae and bottle PRs.
- In this refactor, all of the `brew` "check these things about these
  formulae to see if they're OK to bottle" is done in the
  `find-formulae-to-bottle` step, rather than the `brew
  build-bottle-pr`, so the script that writes commits and raises pull
  requests doesn't have to run any `brew` commands itself, so the
  formulae are never loaded.
- I think I've taken everything necessary out - things seem to work. I
  also reject formulae that can't be bottled, which removes them from the
  final list of formulae that are shown for `brew build-bottle-pr`.

* Move `open_pull_request?` into find-formulae-to-bottle too

* Add a `--remote` argument to specify the git remote if it's not `origin`

- This deletes a load of code to search for the remote that matches
  $HOMEBREW_GITHUB_USER or $USER, because in the Action we're going to
  simplify our lives and push to `origin`. That enables maintainers to
  delete branches after merging PRs, and gives us one fewer fork to
  maintain and sync etc.
- If maintainers still want to use this manually themselves, ie if the
  Action stops working, then they can pass `--remote` as an argument with
  the remote name of their forked repo.

* Add `tap_dir` as an argument, or set it to the Linuxbrew default location

* Audit failures can be fixed in the bottle PRs when they fail CI

* Hardcode `formula_path` as we're already in the tap dir

- The `formula` variable is a string rather than a Formula object in
  this script now, so we can't dynamically find `formula.path`.
- As we're already in `tap-dir`, ugly-ly hardcode
  `Formula/#{formula}.rb` as the path. Then we don't have to load
  formulae into this script.

* Don't need to find dependencies of >1 formula as we go one at a time

- As a result, we can remove the `shell` and `brew` methods.

* Output non-formula output (errors) if the user passes `--verbose`

- Otherwise, in normal output when in use in a shell script to pass the
  output to `brew build-bottle-pr`, this happens:
  ```
Warning: git-extras: Skipping because a PR is open
Warning: git: Skipping because a PR is open
Warning: mmark: Skipping because a PR is open
Error: No available formula with the name "git-extras:"
Error: No available formula with the name "build"
Error: No available formula with the name "a"
Error: No available formula with the name "bottle"
Error: No available formula with the name "for"
Error: No available formula with the name "linuxbrew"
Error: bad URI(is not URI?): (https://github.com/Homebrew/linuxbrew-core/pull/...)
  ```
- This will cause output to be silenced in normal use, but given the
  same HEAD merge commit, re-running manually with `--verbose` will tell
  you what was wrong.

* Don't let formula be a Formula object, pull it from ARGV.last instead

- We were still loading formulae via `ARGV.formulae`. Instead of doing
  that, take the _final_ argument to this script invocation to be the
  formula name, which will be a string and not a formula object.

* Set `HOMEBREW_DISABLE_LOAD_FORMULA` envvar to "1"

- This script _shouldn't_ load formulae any more, but this makes sure.

Things to note for people using it manually in the time between this getting merged and the GitHub Action being merged too:

Pass `--remote=<your-remote-name>` to use a different remote than `origin`.
By default, brew find-formulae-to-bottle` won't tell you why some formulae you just resolved conflicts for don't show up in the bottling list. Pass `--verbose` to see them.